services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt-shwmon
    env_file:
      - .env
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./log:/log
    network_mode: host
    restart: always
