version: "3.7"

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-shwmon
    # env_file:
    #   - .env
    volumes:
      - ./conf:/mosquitto/conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    network_mode: host
    restart: unless-stopped
